# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='roles',
            field=models.IntegerField(choices=[(1, 'Class administrator'), (0, 'School administrator'), (2, 'Task administrator')], default=1, verbose_name='Role'),
        ),
    ]
