# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduly', '0003_auto_20171109_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eduly.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roles',
            field=models.IntegerField(choices=[(1, 'Class administrator'), (0, 'School administrator'), (2, 'Task administrator')], default=1, verbose_name='Role'),
        ),
    ]
