# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduly', '0004_auto_20171109_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduly.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roles',
            field=models.IntegerField(choices=[(0, 'School administrator'), (2, 'Task administrator'), (1, 'Class administrator')], default=1, verbose_name='Role'),
        ),
    ]
